# Generated by Django 4.2.7 on 2026-02-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_equipment', models.IntegerField()),
                ('average_flowrate', models.FloatField()),
                ('average_pressure', models.FloatField()),
                ('average_temperature', models.FloatField()),
                ('type_distribution', models.JSONField()),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
